FROM node:alpine

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ACCESS_REGION

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION=${AWS_ACCESS_REGION}

RUN apk update && apk upgrade && apk add nano
RUN apk --no-cache add python3 py3-pip
RUN  pip3 install --upgrade pip \
  && pip3 install --no-cache-dir awscli

WORKDIR /app

RUN aws s3 cp s3://stralom-deploys/authentication/.env.production /app/.env.production
COPY package.json /app
RUN yarn install

COPY . /app
RUN yarn build
EXPOSE 5000

CMD ["yarn","start:prod"]
