# https://stackoverflow.com/questions/74815121/why-is-hot-reloading-not-working-in-my-nestjs-docker-compose-multistage-project
FROM node:alpine
USER root

WORKDIR /app

COPY package.json /app
RUN yarn install
RUN npm i -g typescript@next
COPY . /app
EXPOSE 3002

USER node

CMD yarn start:dev
